### PR TITLE
Fix/scanner type not recognized

### LINKED ISSUE #5: Scanner type not recognized
when i start the rqt plugin for the scanner i get this warning:
[WARN] [1576571708.299480]: Profile settings disabled. Scanner type not recognized.

I need the profile settings to be enabled to invert the z

I am using the scanner of type 2950-25.
when i print self.scanner type it returns 65536

### PR DESCRIPTION
**Pull request by dave992**
Use the added service calls to `/invert_x` and `/invert_z` to prevent the 'Scanner type not recognized' error, resolves #5

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
For future me (and somewhat for current me): how does flipping the points about a few axes solve "scanner type not recognised" errors?

**Comment by dave992** [comment]
The "scanner type not recognized" error was the result of incorrectly trying to use the GetFeature function of the API to retrieve the scanner type. The two options I considered were to find another way to retrieve the scanner type or remove the need to retrieve the scanner type. 

Adding services to toggle the flipping of the x and z values were already on my list and underway. These services would remove the need to retrieve the scanner type in the GUI, which I why I opted for this solution to fix the bug. 

An added benefit was that the code (some bit flipping) to enable or disable the flipping of coordinate is only in the driver and not also in the GUI code.

**Comment by gavanderhoorn** [comment]
Suggestion: write what you wrote here in a response to me as a commit comment or in the PR description.

I would not have understood these commits out of context otherwise.

**Comment by dave992** [comment]
>Suggestion: write what you wrote here in a response to me as a commit comment or in the PR description.

Updated the PR description and commented on the merge commit to point here for a more elaborate description as well.

**Pull request merged**
