### PR TITLE
Add 30xx-25 description

### PR DESCRIPTION
**Pull request by dave992**
The changes from Rik to add the 30xx-25 description to this package.

### CODE REVIEW

**Comment by dave992** [comment]
The only change I made is dropping the Rviz config changes, as the changes were mostly resizing of the window and changes to the location of the viewpoint. If you need a specific configuration for these test files just create a new config file.

Think this is good too merge. We still need to look at the location of the `base_link`. As this applies to all sensor descriptions, I think it is better to discuss that in the issue and make a separate branch/PR for it. 

@rtonnaer, any comments before I merge this?

**Comment by gavanderhoorn** [comment]
Should 56e8360 be included here?

**Comment by dave992** [comment]
An alternative to that is already in the master branch (which does not rely on hardcoded paths): 01cabc11e689857ffeb8eea6495c193d7b01669b

**Comment by gavanderhoorn** [comment]
> An alternative to that is already in the master branch (which does not rely on hardcoded paths): [01cabc1](https://github.com/sam-xl/scancontrol/commit/01cabc11e689857ffeb8eea6495c193d7b01669b)

Yes, I realise that :)

But 56e8360 is actually part of this PR now. Hence my question: should it be included here (again)?

**Comment by dave992** [comment]
I misread your comment then. That should not be part of this, the last commit (from me) also effectively removes those changes. I will clean up the commit history then.

**Comment by rtonnaer** [comment]
I checked the model again. It looks fine so for me it`s okay to merge.

**Pull request merged**
